/**
 * Copyright (C) 2000-2026 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.testbench.loadtest.util;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import tools.jackson.core.StreamReadConstraints;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.databind.ObjectMapper;

/**
 * Converts HAR files to k6 test scripts. This replaces the npm har-to-k6
 * package with a pure Java implementation.
 */
public class HarToK6Converter {

    private static final Logger log = Logger
            .getLogger(HarToK6Converter.class.getName());
    private static final Pattern SYNC_CLIENT_ID_PATTERN = Pattern
            .compile("\"syncId\":-?\\d+,\"clientId\":-?\\d+");

    /** Matches v-uiId=N in URLs (any numeric value). */
    private static final Pattern UI_ID_URL_PATTERN = Pattern
            .compile("v-uiId=\\d+");

    /** Matches csrfToken UUID in UIDL POST bodies. */
    private static final Pattern CSRF_TOKEN_BODY_PATTERN = Pattern.compile(
            "\"csrfToken\":\"([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\"");

    /**
     * Matches select/setDetailsVisible calls with entity key args in UIDL
     * bodies.
     */
    private static final Pattern ENTITY_KEY_ARG_PATTERN = Pattern.compile(
            "\"templateEventMethodName\":\"(select|setDetailsVisible)\",\"templateEventMethodArgs\":\\[\"(\\d+)\"\\]");

    /** Matches mSync input values (user-entered form data) in UIDL bodies. */
    private static final Pattern MSYNC_INPUT_VALUE_PATTERN = Pattern.compile(
            "\"type\":\"mSync\",\"node\":\\d+,\"feature\":\\d+,\"property\":\"value\",\"value\":\"([^\"]+)\"");

    private static final String K6_SCRIPT_IMPORTS = """
            // Auto-generated by testbench-converter-plugin

            import http from 'k6/http'
            import { check, fail } from 'k6'
            import { sleep } from 'k6'

            """;

    private static final String K6_SCRIPT_FUNCTION_START = """
            export default function () {
            """;

    private static final String K6_SCRIPT_FOOTER = """
            }
            """;

    /**
     * Collected mSync input values across all requests during a single
     * conversion.
     */
    private final List<String> collectedInputValues = new ArrayList<>();

    private final ObjectMapper objectMapper;

    public HarToK6Converter() {
        JsonFactory jsonFactory = JsonFactory.builder()
                .streamReadConstraints(StreamReadConstraints.builder()
                        .maxStringLength(Integer.MAX_VALUE).build())
                .build();
        this.objectMapper = JsonMapper.builder(jsonFactory).build();
    }

    /**
     * Converts a HAR file to a k6 test script with default thresholds.
     *
     * @param harFile
     *            the input HAR file
     * @param outputFile
     *            the output k6 test script
     * @throws IOException
     *             if reading or writing fails
     */
    public void convert(Path harFile, Path outputFile) throws IOException {
        convert(harFile, outputFile, ThresholdConfig.DEFAULT);
    }

    /**
     * Converts a HAR file to a k6 test script with configurable thresholds.
     *
     * @param harFile
     *            the input HAR file
     * @param outputFile
     *            the output k6 test script
     * @param thresholdConfig
     *            threshold configuration for the generated script
     * @throws IOException
     *             if reading or writing fails
     */
    public void convert(Path harFile, Path outputFile,
            ThresholdConfig thresholdConfig) throws IOException {
        log.info("Converting HAR to k6 test...");
        collectedInputValues.clear();

        HarFile har = objectMapper.readValue(harFile.toFile(), HarFile.class);

        List<HarEntry> entries = har.log().entries();
        log.info("  Processing " + entries.size() + " requests...");

        // Detect Vaadin session values to make them dynamic per VU
        VaadinSessionInfo session = detectVaadinSession(entries);

        StringBuilder script = new StringBuilder();
        script.append(K6_SCRIPT_IMPORTS);
        script.append("export const options = {\n");
        script.append(thresholdConfig.toK6ThresholdsBlock());
        script.append("}\n\n");
        script.append(K6_SCRIPT_FUNCTION_START);

        for (int i = 0; i < entries.size(); i++) {
            HarEntry entry = entries.get(i);
            // Calculate time delta from previous request
            long deltaMs = -1;
            if (i > 0) {
                deltaMs = calculateDeltaMs(entries.get(i - 1), entry);
            }
            String requestCode = generateRequestCode(entry, i, deltaMs,
                    session);
            script.append(requestCode);

            // Request label for error messages (e.g., "Request 6 (GET
            // ...v-r=init...)")
            String requestLabel = "Request " + (i + 1) + " ("
                    + entry.request().method() + " "
                    + truncateUrl(entry.request().url()) + ")";

            // After first init request, inject code to declare and extract
            // Vaadin session values
            if (session != null && i == session.initRequestIndex()) {
                script.append(generateSessionExtractionCode(requestLabel));
            }

            // After subsequent init requests (e.g., post-login), re-extract
            // session values
            if (session != null && session.isSubsequentInitRequest(i)) {
                script.append(generateSessionReExtractionCode());
            }

            // After each UIDL POST, extract syncId from response and increment
            // clientId
            if (session != null && isUidlRequest(entry)) {
                script.append(generateUidlResponseExtractionCode(requestLabel));
            }
        }

        script.append(K6_SCRIPT_FOOTER);

        String scriptContent = script.toString();

        // If mSync input values were detected, add CSV data loading to the
        // script
        if (!collectedInputValues.isEmpty()) {
            scriptContent = addCsvDataLoading(scriptContent, outputFile);
            Path csvFile = deriveCsvPath(outputFile);
            writeCsvFile(csvFile);
            log.info("  Input data CSV: " + csvFile + " ("
                    + collectedInputValues.size() + " fields)");
        }

        Files.writeString(outputFile, scriptContent);
        log.info("HAR converted to k6 test: " + outputFile);
    }

    /**
     * Generates k6 request code for a HAR entry.
     *
     * @param entry
     *            the HAR entry
     * @param index
     *            the request index
     * @param deltaMs
     *            time delta from previous request in milliseconds, or -1 for
     *            first request
     * @param session
     *            detected Vaadin session info, or null if not a Vaadin app
     */
    private String generateRequestCode(HarEntry entry, int index, long deltaMs,
            VaadinSessionInfo session) {
        HarRequest request = entry.request();
        String method = request.method().toUpperCase();
        String url = request.url();

        // Determine if this request needs dynamic Vaadin session values
        boolean pastInit = session != null
                && index > session.initRequestIndex();
        boolean dynamicUrl = pastInit && UI_ID_URL_PATTERN.matcher(url).find();

        StringBuilder code = new StringBuilder();
        // Include HAR timing delta as a comment for the refactorer to use
        if (deltaMs >= 0) {
            code.append("  // HAR_DELTA_MS: ").append(deltaMs).append("\n");
        }
        code.append("  // Request ").append(index + 1).append(": ")
                .append(method).append(" ").append(truncateUrl(url))
                .append("\n");

        // Generate headers object, skipping Cookie headers (k6 cookie jar
        // handles these)
        StringBuilder headers = new StringBuilder();
        headers.append("{\n");
        if (request.headers() != null && !request.headers().isEmpty()) {
            List<String> headerLines = new ArrayList<>();
            for (HarHeader header : request.headers()) {
                String name = header.name().toLowerCase();
                // Skip pseudo-headers, auto-generated headers, cookies, and
                // encoding
                // (Accept-Encoding is removed so server returns uncompressed
                // responses
                // that can be parsed for Vaadin session values)
                if (name.startsWith(":") || name.equals("content-length")
                        || name.equals("host") || name.equals("connection")
                        || name.equals("cookie")
                        || name.equals("accept-encoding")) {
                    continue;
                }
                headerLines.add("      '" + escapeJs(header.name()) + "': '"
                        + escapeJs(header.value()) + "'");
            }
            headers.append(String.join(",\n", headerLines));
            if (!headerLines.isEmpty()) {
                headers.append("\n");
            }
        }
        headers.append("    }");

        // Note: cookies are NOT added as headers — k6 cookie jar manages
        // JSESSIONID automatically

        // Generate the request (use 'let' only for first request)
        String responseDecl = index == 0 ? "let response" : "response";

        if ("GET".equals(method) || "HEAD".equals(method)
                || "OPTIONS".equals(method)) {
            code.append("  ").append(responseDecl).append(" = http.")
                    .append(method.toLowerCase()).append("(\n");
            if (dynamicUrl) {
                String escapedUrl = UI_ID_URL_PATTERN
                        .matcher(escapeJsTemplate(url))
                        .replaceAll(Matcher.quoteReplacement("v-uiId=${uiId}"));
                code.append("    `").append(escapedUrl).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(url)).append("',\n");
            }
            code.append("    {\n");
            code.append("      headers: ").append(headers).append("\n");
            code.append("    }\n");
            code.append("  )\n\n");
        } else {
            // POST, PUT, PATCH, DELETE with body
            String body = "";
            if (request.postData() != null
                    && request.postData().text() != null) {
                body = request.postData().text();
            }
            boolean hasCsrfToken = pastInit
                    && CSRF_TOKEN_BODY_PATTERN.matcher(body).find();
            boolean hasSyncCounters = pastInit
                    && SYNC_CLIENT_ID_PATTERN.matcher(body).find();
            // Detect mSync input values (user-entered form data)
            List<String> msyncValues = new ArrayList<>();
            boolean hasMsyncInputs = false;
            if (pastInit) {
                Matcher msyncMatcher = MSYNC_INPUT_VALUE_PATTERN.matcher(body);
                while (msyncMatcher.find()) {
                    msyncValues.add(msyncMatcher.group(1));
                    hasMsyncInputs = true;
                }
            }
            // Body needs template literals if it contains any dynamic values
            boolean dynamicBody = hasCsrfToken || hasSyncCounters
                    || hasMsyncInputs;

            // Detect grid entity key args in select/setDetailsVisible calls
            String entityKey = null;
            if (dynamicBody) {
                Matcher entityKeyMatcher = ENTITY_KEY_ARG_PATTERN.matcher(body);
                if (entityKeyMatcher.find()) {
                    entityKey = entityKeyMatcher.group(2);
                }
            }

            // Pick a random grid key before requests that select/edit entities
            if (entityKey != null) {
                code.append(
                        "  selectedKey = gridKeys.length > 0 ? gridKeys[Math.floor(Math.random() * gridKeys.length)] : '0'\n");
            }

            code.append("  ").append(responseDecl).append(" = http.")
                    .append(method.toLowerCase()).append("(\n");

            if (dynamicUrl) {
                String escapedUrl = UI_ID_URL_PATTERN
                        .matcher(escapeJsTemplate(url))
                        .replaceAll(Matcher.quoteReplacement("v-uiId=${uiId}"));
                code.append("    `").append(escapedUrl).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(url)).append("',\n");
            }

            if (dynamicBody) {
                String escapedBody = escapeJsTemplate(body);
                // Replace hardcoded csrfToken UUID with dynamic variable
                if (hasCsrfToken) {
                    escapedBody = CSRF_TOKEN_BODY_PATTERN.matcher(escapedBody)
                            .replaceAll(Matcher.quoteReplacement(
                                    "\"csrfToken\":\"${csrfToken}\""));
                }
                // Replace hardcoded syncId/clientId with dynamic variables
                if (hasSyncCounters) {
                    escapedBody = SYNC_CLIENT_ID_PATTERN.matcher(escapedBody)
                            .replaceFirst(Matcher.quoteReplacement(
                                    "\"syncId\":${syncId},\"clientId\":${clientId}"));
                }
                // Replace hardcoded entity keys with dynamic grid key
                if (entityKey != null) {
                    escapedBody = escapedBody.replace(
                            "templateEventMethodArgs\":[\"" + entityKey + "\"]",
                            "templateEventMethodArgs\":[\"${selectedKey}\"]");
                }
                // Replace mSync input values with CSV data references
                for (String msyncValue : msyncValues) {
                    int inputIndex = collectedInputValues.size() + 1; // 1-based
                    collectedInputValues.add(msyncValue);
                    String escapedValue = escapeJsTemplate(msyncValue);
                    escapedBody = escapedBody.replaceFirst(
                            Pattern.quote("\"property\":\"value\",\"value\":\""
                                    + escapedValue + "\""),
                            Matcher.quoteReplacement(
                                    "\"property\":\"value\",\"value\":\"${inputRow.input_"
                                            + inputIndex + "}\""));
                }
                code.append("    `").append(escapedBody).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(body)).append("',\n");
            }

            code.append("    {\n");
            code.append("      headers: ").append(headers).append("\n");
            code.append("    }\n");
            code.append("  )\n\n");
        }

        return code.toString();
    }

    /**
     * Detects Vaadin session values from HAR entries. Finds all init requests,
     * recorded JSESSIONID, csrfToken, and uiId. Supports login flows where a
     * second init request occurs after authentication.
     *
     * @return session info if a Vaadin init request is found, null otherwise
     */
    private VaadinSessionInfo detectVaadinSession(List<HarEntry> entries) {
        int firstInitRequestIndex = -1;
        List<Integer> allInitRequestIndices = new ArrayList<>();
        String jsessionId = null;
        String csrfToken = null;
        String uiId = null;

        Pattern csrfPattern = Pattern
                .compile("\"csrfToken\"\\s*:\\s*\"([^\"]+)\"");
        Pattern uiIdPattern = Pattern.compile("v-uiId=(\\d+)");

        for (int i = 0; i < entries.size(); i++) {
            HarEntry entry = entries.get(i);
            String url = entry.request().url();

            // Find all init requests (login flows have multiple)
            if (url.contains("v-r=init")) {
                allInitRequestIndices.add(i);
                if (firstInitRequestIndex == -1) {
                    firstInitRequestIndex = i;
                }
            }

            // Find JSESSIONID from cookies
            if (jsessionId == null && entry.request().cookies() != null) {
                for (HarCookie cookie : entry.request().cookies()) {
                    if ("JSESSIONID".equalsIgnoreCase(cookie.name())) {
                        jsessionId = cookie.value();
                        break;
                    }
                }
            }

            // Find csrfToken from POST body
            if (csrfToken == null && entry.request().postData() != null
                    && entry.request().postData().text() != null) {
                Matcher m = csrfPattern
                        .matcher(entry.request().postData().text());
                if (m.find()) {
                    csrfToken = m.group(1);
                }
            }

            // Find uiId from URL
            if (uiId == null) {
                Matcher m = uiIdPattern.matcher(url);
                if (m.find()) {
                    uiId = m.group(1);
                }
            }
        }

        if (firstInitRequestIndex >= 0) {
            log.info(
                    "  Detected Vaadin session: initRequests="
                            + allInitRequestIndices.size() + " (first=#"
                            + (firstInitRequestIndex + 1) + ")" + ", uiId="
                            + uiId + ", csrfToken="
                            + (csrfToken != null ? csrfToken.substring(0,
                                    Math.min(8, csrfToken.length())) + "..."
                                    : "null"));
            return new VaadinSessionInfo(firstInitRequestIndex,
                    allInitRequestIndices, jsessionId, csrfToken, uiId);
        }
        return null;
    }

    /**
     * Generates k6 code to extract Vaadin session values from the init
     * response. This code is injected after the init request in the generated
     * script.
     *
     * @param requestLabel
     *            human-readable label for error messages (e.g., "Request 6 (GET
     *            ...)")
     */
    private String generateSessionExtractionCode(String requestLabel) {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Abort iteration and trigger test abort if init response is invalid\n");
        code.append("  if (!check(response, {\n");
        code.append("    'init request succeeded': (r) => r.status === 200,\n");
        code.append(
                "    'session is valid': (r) => !r.body.includes('Your session needs to be refreshed'),\n");
        code.append(
                "    'valid init response': (r) => r.body.includes('\"v-uiId\"') && r.body.includes('\"Vaadin-Security-Key\"'),\n");
        code.append("  })) {\n");
        code.append("    fail(`").append(escapeJsTemplate(requestLabel)).append(
                ": init failed (status ${response.status}): ${response.body.substring(0, 200)}`)\n");
        code.append("  }\n\n");
        code.append("  // Extract Vaadin session values from init response\n");
        code.append(
                "  let uiId = response.body.match(/\"v-uiId\"\\s*:\\s*(\\d+)/)[1]\n");
        code.append(
                "  let csrfToken = response.body.match(/\"Vaadin-Security-Key\"\\s*:\\s*\"([^\"]+)\"/)[1]\n");
        code.append("  let syncId = 0\n");
        code.append("  let clientId = 0\n");
        code.append("  let gridKeys = []\n");
        code.append("  let selectedKey = '0'\n");
        code.append("\n");
        return code.toString();
    }

    /**
     * Generates k6 code to re-extract Vaadin session values after a subsequent
     * init request (e.g., after login when the security key changes). Uses
     * reassignment instead of let declarations since variables already exist.
     */
    private String generateSessionReExtractionCode() {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Re-extract Vaadin session values after login/navigation\n");
        code.append(
                "  if (response.status === 200 && response.body.includes('\"Vaadin-Security-Key\"')) {\n");
        code.append(
                "    var newUiId = response.body.match(/\"v-uiId\"\\s*:\\s*(\\d+)/)\n");
        code.append(
                "    var newCsrf = response.body.match(/\"Vaadin-Security-Key\"\\s*:\\s*\"([^\"]+)\"/)\n");
        code.append("    if (newUiId) uiId = newUiId[1]\n");
        code.append("    if (newCsrf) csrfToken = newCsrf[1]\n");
        code.append("    syncId = 0\n");
        code.append("    clientId = 0\n");
        code.append("  }\n");
        code.append("\n");
        return code.toString();
    }

    /**
     * Generates k6 code to extract syncId from a UIDL response and increment
     * clientId. Injected after each UIDL POST in the generated script.
     *
     * @param requestLabel
     *            human-readable label for error messages (e.g., "Request 10
     *            (POST ...)")
     */
    private String generateUidlResponseExtractionCode(String requestLabel) {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Abort iteration and trigger test abort if UIDL response is invalid\n");
        code.append(
                "  var syncIdMatch = response.body.match(/\"syncId\"\\s*:\\s*(-?\\d+)/)\n");
        code.append("  if (!check(response, {\n");
        code.append("    'UIDL request succeeded': (r) => r.status === 200,\n");
        code.append(
                "    'no server error': (r) => !r.body.includes('\"appError\"'),\n");
        code.append(
                "    'no exception': (r) => !r.body.includes('Exception'),\n");
        code.append(
                "    'session is valid': (r) => !r.body.includes('Your session needs to be refreshed'),\n");
        code.append(
                "    'security key valid': (r) => !r.body.includes('Invalid security key'),\n");
        code.append("    'valid UIDL response': () => syncIdMatch !== null,\n");
        code.append("  })) {\n");
        code.append("    fail(`").append(escapeJsTemplate(requestLabel)).append(
                ": UIDL failed (status ${response.status}): ${response.body.substring(0, 200)}`)\n");
        code.append("  }\n\n");
        code.append(
                "  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)\n");
        code.append("  syncId = Math.max(0, parseInt(syncIdMatch[1]))\n");
        code.append("  clientId++\n");
        code.append(
                "  // Extract grid item keys from response (used for select/edit operations)\n");
        code.append(
                "  var found = response.body.match(/\"key\":\"[^\"]+\"/g)\n");
        code.append(
                "  if (found) gridKeys = found.map(s => s.split('\"')[3])\n");
        code.append("\n");
        return code.toString();
    }

    /**
     * Checks if a HAR entry is a Vaadin UIDL request.
     */
    private boolean isUidlRequest(HarEntry entry) {
        return "POST".equalsIgnoreCase(entry.request().method())
                && entry.request().url().contains("v-r=uidl");
    }

    /**
     * Holds Vaadin session values detected from the recorded HAR file.
     */
    record VaadinSessionInfo(int initRequestIndex,
            List<Integer> allInitRequestIndices, String recordedJsessionId,
            String recordedCsrfToken, String recordedUiId) {
        /**
         * Returns true if the given index is an init request (but not the first
         * one).
         */
        boolean isSubsequentInitRequest(int index) {
            return allInitRequestIndices.contains(index)
                    && index != initRequestIndex;
        }
    }

    /**
     * Calculates time delta in milliseconds between two requests.
     *
     * @param previous
     *            the previous HAR entry
     * @param current
     *            the current HAR entry
     * @return time delta in milliseconds, or 0 if unable to calculate
     */
    private long calculateDeltaMs(HarEntry previous, HarEntry current) {
        try {
            if (previous.startedDateTime() != null
                    && current.startedDateTime() != null) {
                Instant prevTime = Instant.parse(previous.startedDateTime());
                Instant currTime = Instant.parse(current.startedDateTime());
                return Math.max(0,
                        currTime.toEpochMilli() - prevTime.toEpochMilli());
            }
        } catch (Exception e) {
            // Ignore parse errors
        }
        return 0;
    }

    /**
     * Truncates URL for display in comments.
     */
    private String truncateUrl(String url) {
        if (url.length() > 80) {
            return url.substring(0, 77) + "...";
        }
        return url;
    }

    /**
     * Escapes a string for use in a JavaScript single-quoted string.
     */
    private String escapeJs(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("\\", "\\\\").replace("'", "\\'")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }

    /**
     * Escapes a string for use in a JavaScript template literal (backtick
     * string). Does NOT escape ${} — the caller is responsible for inserting
     * template expressions after calling this method.
     */
    private String escapeJsTemplate(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("\\", "\\\\").replace("`", "\\`")
                .replace("${", "\\${").replace("\n", "\\n").replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    // ── CSV input data support ─────────────────────────────────────────

    /**
     * Injects SharedArray import and CSV loading code into the generated
     * script. The CSV file contains recorded input values that can be expanded
     * by the user to provide different data for each virtual user.
     */
    private String addCsvDataLoading(String scriptContent, Path outputFile) {
        String csvFileName = deriveCsvPath(outputFile).getFileName().toString();

        // Add SharedArray import after existing imports
        scriptContent = scriptContent.replace("import { sleep } from 'k6'",
                "import { sleep } from 'k6'\nimport { SharedArray } from 'k6/data'");

        // Add CSV loading code and input row selection
        String csvLoadBlock = "\n"
                + "// Input test data from CSV — add rows to " + csvFileName
                + " for per-VU variation\n"
                + "const inputData = new SharedArray('input data', function () {\n"
                + "  const lines = open('./" + csvFileName
                + "').split('\\n').filter(l => l.trim())\n"
                + "  const headers = lines[0].split(',')\n"
                + "  return lines.slice(1).filter(l => l.trim()).map(line => {\n"
                + "    const values = line.split(',')\n"
                + "    const obj = {}\n"
                + "    headers.forEach((h, i) => obj[h.trim()] = (values[i] || '').trim())\n"
                + "    return obj\n" + "  })\n" + "})\n";

        String inputRowSelection = "  // Pick a random row from the input data CSV\n"
                + "  const inputRow = inputData[Math.floor(Math.random() * inputData.length)]\n\n";

        scriptContent = scriptContent.replace("export default function () {\n",
                csvLoadBlock + "\nexport default function () {\n"
                        + inputRowSelection);

        return scriptContent;
    }

    /**
     * Derives the CSV data file path from the k6 output file path. Strips
     * "-generated" suffix if present so both generated and refactored scripts
     * reference the same CSV file.
     */
    private Path deriveCsvPath(Path outputFile) {
        String fileName = outputFile.getFileName().toString();
        String csvName;
        if (fileName.endsWith("-generated.js")) {
            csvName = fileName.replace("-generated.js", "-data.csv");
        } else {
            csvName = fileName.replace(".js", "-data.csv");
        }
        return outputFile.resolveSibling(csvName);
    }

    /**
     * Writes the collected input values to a CSV file. The first row contains
     * column headers (input_1, input_2, ...). The second row contains the
     * values recorded during the TestBench test. Users can add more rows to
     * provide different data for each virtual user; if only the recorded row is
     * present it will be used for all VUs.
     */
    private void writeCsvFile(Path csvFile) throws IOException {
        StringBuilder csv = new StringBuilder();
        // Header row
        for (int i = 0; i < collectedInputValues.size(); i++) {
            if (i > 0)
                csv.append(',');
            csv.append("input_").append(i + 1);
        }
        csv.append('\n');
        // Data row with recorded values
        for (int i = 0; i < collectedInputValues.size(); i++) {
            if (i > 0)
                csv.append(',');
            csv.append(escapeCsvValue(collectedInputValues.get(i)));
        }
        csv.append('\n');
        Files.writeString(csvFile, csv.toString());
    }

    /**
     * Escapes a value for CSV output (RFC 4180). Wraps in double quotes if the
     * value contains commas, quotes, or newlines.
     */
    private static String escapeCsvValue(String value) {
        if (value.contains(",") || value.contains("\"") || value.contains("\n")
                || value.contains("\r")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    // HAR format DTOs using Java records
    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarFile(HarLog log) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarLog(String version, HarCreator creator, List<HarEntry> entries,
            List<HarPage> pages) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarCreator(String name, String version) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarPage(String startedDateTime, String id, String title) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarEntry(String startedDateTime, Double time, HarRequest request,
            HarResponse response) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarRequest(String method, String url, String httpVersion,
            List<HarHeader> headers, List<HarCookie> cookies,
            HarPostData postData) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarResponse(Integer status, String statusText,
            List<HarHeader> headers, HarContent content) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarHeader(String name, String value) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarCookie(String name, String value) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarPostData(String mimeType, String text) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarContent(Long size, String mimeType, String text) {
    }
}
