/**
 * Copyright (C) 2000-2026 Vaadin Ltd
 *
 * This program is available under Vaadin Commercial License and Service Terms.
 *
 * See <https://vaadin.com/commercial-license-and-service-terms> for the full
 * license.
 */
package com.vaadin.testbench.loadtest.util;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import tools.jackson.core.StreamReadConstraints;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

/**
 * Converts HAR files to k6 test scripts. This replaces the npm har-to-k6
 * package with a pure Java implementation.
 */
public class HarToK6Converter {

    private static final Logger log = Logger
            .getLogger(HarToK6Converter.class.getName());
    private static final Pattern SYNC_CLIENT_ID_PATTERN = Pattern
            .compile("\"syncId\":-?\\d+,\"clientId\":-?\\d+");

    /** Matches v-uiId=N in URLs (any numeric value). */
    private static final Pattern UI_ID_URL_PATTERN = Pattern
            .compile("v-uiId=\\d+");

    /** Matches csrfToken UUID in UIDL POST bodies. */
    private static final Pattern CSRF_TOKEN_BODY_PATTERN = Pattern.compile(
            "\"csrfToken\":\"([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\"");

    /**
     * Matches select/setDetailsVisible calls with entity key args in UIDL
     * bodies.
     */
    private static final Pattern ENTITY_KEY_ARG_PATTERN = Pattern.compile(
            "\"templateEventMethodName\":\"(select|setDetailsVisible)\",\"templateEventMethodArgs\":\\[\"(\\d+)\"\\]");

    /** Matches mSync input values (user-entered form data) in UIDL bodies. */
    private static final Pattern MSYNC_INPUT_VALUE_PATTERN = Pattern.compile(
            "\"type\":\"mSync\",\"node\":\\d+,\"feature\":\\d+,\"property\":\"value\",\"value\":\"((?:[^\"\\\\]|\\\\.)*)\"");

    /**
     * Matches positive {@code "node":N} occurrences in UIDL request bodies.
     * Negative node IDs are client-side temporary nodes and are not server-
     * assigned, so they are intentionally excluded.
     */
    private static final Pattern POSITIVE_NODE_ID_PATTERN = Pattern
            .compile("\"node\":(\\d+)");

    /** Prefix Vaadin UIDL responses carry to defeat script-tag injection. */
    private static final String UIDL_RESPONSE_PREFIX = "for(;;);";

    private static final String K6_SCRIPT_IMPORTS = """
            // Auto-generated by testbench-converter-plugin

            import http from 'k6/http'
            import { check, fail } from 'k6'
            import { sleep } from 'k6'
            import { textSummary } from '../utils/k6-summary.js'

            """;

    /**
     * Extra imports pulled from {@code vaadin-k6-helpers.js} when runtime
     * node-ID resolution is enabled.
     */
    private static final String NODE_RESOLVER_IMPORT = "import { updateNodeMap, resolveNode } from '../utils/vaadin-k6-helpers.js'\n";

    private static final String K6_SCRIPT_FUNCTION_START = """
            export default function () {
            """;

    private static final String K6_SCRIPT_FOOTER = """
            }
            """;

    /**
     * Shared handleSummary function injected into all generated scripts. Writes
     * the full summary (including per-request sub-metrics) as JSON and
     * preserves the console text summary.
     */
    static final String HANDLE_SUMMARY_FUNCTION = """

            export function handleSummary(data) {
              // Compact console summary — keep only the headline metrics.
              // Full metric set (including per-request sub-metrics) still
              // goes to the JSON file when SUMMARY_FILE is set.
              const keepMetrics = new Set([
                'checks', 'http_req_duration', 'http_req_failed',
                'http_reqs', 'iterations',
              ])
              const consoleData = Object.assign({}, data, {
                metrics: Object.fromEntries(
                  Object.entries(data.metrics).filter(([key]) => keepMetrics.has(key))
                )
              })
              const result = {
                'stdout': textSummary(consoleData, { indent: ' ', enableColors: true }),
              }
              if (__ENV.SUMMARY_FILE) {
                result[__ENV.SUMMARY_FILE] = JSON.stringify(data, null, 2)
              }
              return result
            }
            """;

    /**
     * Collected mSync input values across all requests during a single
     * conversion.
     */
    private final List<String> collectedInputValues = new ArrayList<>();

    /**
     * Conversion-time map from recorded (server-assigned) node IDs to a stable
     * key derived from {@code id} attributes or tag+ordinal fallbacks. Used to
     * rewrite positive {@code "node":N} occurrences in UIDL request bodies.
     */
    private final Map<Integer, String> nodeIdToStableKey = new HashMap<>();

    /**
     * Per-tag ordinal counter used to derive {@code tag#N} fallback keys when a
     * node has no {@code id} attribute. Counting mirrors the runtime helper so
     * keys stay stable across conversion runs.
     */
    private final Map<String, Integer> ordinalByTag = new HashMap<>();

    /**
     * Scenario name prefix for request tags, derived from the output file name.
     * E.g., "hello-world" from "hello-world-generated.js".
     */
    private String scenarioName;

    private final ObjectMapper objectMapper;

    /**
     * When {@code true}, emits runtime node-ID resolution scaffolding and
     * rewrites positive {@code "node":N} UIDL payload references as
     * {@code ${resolveNode(nodeMap, 'stable-key')}}. When {@code false}, the
     * converter emits the legacy literal-number behaviour — useful as an escape
     * hatch for unanticipated UIDL shapes.
     */
    private final boolean resolveNodeIds;

    /**
     * Creates a new HAR to k6 converter with runtime node-ID resolution
     * enabled.
     */
    public HarToK6Converter() {
        this(true);
    }

    /**
     * Creates a new HAR to k6 converter.
     *
     * @param resolveNodeIds
     *            {@code true} to emit runtime node-ID resolution scaffolding;
     *            {@code false} to keep the literal-number behaviour
     */
    public HarToK6Converter(boolean resolveNodeIds) {
        JsonFactory jsonFactory = JsonFactory.builder()
                .streamReadConstraints(StreamReadConstraints.builder()
                        .maxStringLength(Integer.MAX_VALUE).build())
                .build();
        this.objectMapper = JsonMapper.builder(jsonFactory).build();
        this.resolveNodeIds = resolveNodeIds;
    }

    /**
     * Converts a HAR file to a k6 test script with default thresholds.
     *
     * @param harFile
     *            the input HAR file
     * @param outputFile
     *            the output k6 test script
     * @throws IOException
     *             if reading or writing fails
     */
    public void convert(Path harFile, Path outputFile) throws IOException {
        convert(harFile, outputFile, ThresholdConfig.DEFAULT);
    }

    /**
     * Converts a HAR file to a k6 test script with configurable thresholds.
     *
     * @param harFile
     *            the input HAR file
     * @param outputFile
     *            the output k6 test script
     * @param thresholdConfig
     *            threshold configuration for the generated script
     * @throws IOException
     *             if reading or writing fails
     */
    public void convert(Path harFile, Path outputFile,
            ThresholdConfig thresholdConfig) throws IOException {
        convert(harFile, outputFile, thresholdConfig,
                ResponseCheckConfig.EMPTY);
    }

    /**
     * Converts a HAR file to a k6 test script with configurable thresholds and
     * custom response checks.
     *
     * @param harFile
     *            the input HAR file
     * @param outputFile
     *            the output k6 test script
     * @param thresholdConfig
     *            threshold configuration for the generated script
     * @param responseCheckConfig
     *            custom response validation checks to inject
     * @throws IOException
     *             if reading or writing fails
     */
    public void convert(Path harFile, Path outputFile,
            ThresholdConfig thresholdConfig,
            ResponseCheckConfig responseCheckConfig) throws IOException {
        log.info("Converting HAR to k6 test...");
        collectedInputValues.clear();
        nodeIdToStableKey.clear();
        ordinalByTag.clear();

        // Derive scenario name from output file (e.g., "hello-world" from
        // "hello-world-generated.js")
        String fileName = outputFile.getFileName().toString();
        scenarioName = fileName.replaceAll("-generated\\.js$", "")
                .replaceAll("\\.js$", "");

        HarFile har = objectMapper.readValue(harFile.toFile(), HarFile.class);

        List<HarEntry> entries = har.log().entries();
        log.info("  Processing " + entries.size() + " requests...");

        // Detect Vaadin session values to make them dynamic per VU
        VaadinSessionInfo session = detectVaadinSession(entries);

        // Pre-compute request tags for per-request sub-metrics in summary
        List<String> requestTags = new ArrayList<>();
        for (int i = 0; i < entries.size(); i++) {
            HarEntry entry = entries.get(i);
            String method = entry.request().method().toUpperCase();
            if (HarFilter.K6_SUPPORTED_METHODS.contains(method)) {
                requestTags.add(requestTag(i, method, entry.request().url()));
            }
        }

        StringBuilder script = new StringBuilder();
        script.append(K6_SCRIPT_IMPORTS);
        if (resolveNodeIds && session != null) {
            script.append(NODE_RESOLVER_IMPORT).append('\n');
        }
        script.append("export const options = {\n");
        script.append(thresholdConfig.toK6ThresholdsBlock(requestTags));
        script.append("}\n\n");
        script.append(K6_SCRIPT_FUNCTION_START);

        for (int i = 0; i < entries.size(); i++) {
            HarEntry entry = entries.get(i);

            // Skip unsupported HTTP methods (safety net for unfiltered HAR
            // files)
            String method = entry.request().method().toUpperCase();
            if (!HarFilter.K6_SUPPORTED_METHODS.contains(method)) {
                log.warning("  Skipping unsupported HTTP method: " + method
                        + " " + truncateUrl(entry.request().url()));
                continue;
            }

            // Calculate time delta from previous request
            long deltaMs = -1;
            if (i > 0) {
                deltaMs = calculateDeltaMs(entries.get(i - 1), entry);
            }
            String requestCode = generateRequestCode(entry, i, deltaMs,
                    session);
            script.append(requestCode);

            // Request label for error messages (e.g., "Request 6 (GET
            // ...v-r=init...)")
            String requestLabel = "Request " + (i + 1) + " ("
                    + entry.request().method() + " "
                    + truncateUrl(entry.request().url()) + ")";

            // After first init request, inject code to declare and extract
            // Vaadin session values
            if (session != null && i == session.initRequestIndex()) {
                script.append(generateSessionExtractionCode(requestLabel,
                        responseCheckConfig));
            }

            // After subsequent init requests (e.g., post-login), re-extract
            // session values
            if (session != null && session.isSubsequentInitRequest(i)) {
                script.append(generateSessionReExtractionCode());
            }

            // After each UIDL POST, extract syncId from response and increment
            // clientId
            if (session != null && isUidlRequest(entry)) {
                script.append(generateUidlResponseExtractionCode(requestLabel,
                        responseCheckConfig));
            }

            // Populate the conversion-time node-ID map from recorded Vaadin
            // UIDL responses so that subsequent request bodies referencing
            // these nodes can be rewritten with stable keys.
            if (resolveNodeIds && isVaadinResponseEntry(entry)) {
                registerChangesFromResponse(responseBodyText(entry));
            }
        }

        script.append(K6_SCRIPT_FOOTER);
        script.append(HANDLE_SUMMARY_FUNCTION);

        String scriptContent = script.toString();

        // If mSync input values were detected, add CSV data loading to the
        // script
        if (!collectedInputValues.isEmpty()) {
            scriptContent = addCsvDataLoading(scriptContent, outputFile);
            Path csvFile = deriveCsvPath(outputFile);
            writeCsvFile(csvFile);
            log.info("  Input data CSV: " + csvFile + " ("
                    + collectedInputValues.size() + " fields)");
        }

        Files.writeString(outputFile, scriptContent);
        log.info("HAR converted to k6 test: " + outputFile);
    }

    /**
     * Generates k6 request code for a HAR entry.
     *
     * @param entry
     *            the HAR entry
     * @param index
     *            the request index
     * @param deltaMs
     *            time delta from previous request in milliseconds, or -1 for
     *            first request
     * @param session
     *            detected Vaadin session info, or null if not a Vaadin app
     * @return the generated k6 request code
     */
    private String generateRequestCode(HarEntry entry, int index, long deltaMs,
            VaadinSessionInfo session) {
        HarRequest request = entry.request();
        String method = request.method().toUpperCase();
        String url = request.url();

        // Determine if this request needs dynamic Vaadin session values
        boolean pastInit = session != null
                && index > session.initRequestIndex();
        boolean dynamicUrl = pastInit && UI_ID_URL_PATTERN.matcher(url).find();

        StringBuilder code = new StringBuilder();
        // Include HAR timing delta as a comment for the refactorer to use
        if (deltaMs >= 0) {
            code.append("  // HAR_DELTA_MS: ").append(deltaMs).append("\n");
        }
        code.append("  // Request ").append(index + 1).append(": ")
                .append(method).append(" ").append(truncateUrl(url))
                .append("\n");

        // Generate headers object, skipping Cookie headers (k6 cookie jar
        // handles these)
        StringBuilder headers = new StringBuilder();
        headers.append("{\n");
        if (request.headers() != null && !request.headers().isEmpty()) {
            List<String> headerLines = new ArrayList<>();
            for (HarHeader header : request.headers()) {
                String name = header.name().toLowerCase();
                // Skip pseudo-headers, auto-generated headers, cookies, and
                // encoding
                // (Accept-Encoding is removed so server returns uncompressed
                // responses
                // that can be parsed for Vaadin session values)
                if (name.startsWith(":") || name.equals("content-length")
                        || name.equals("host") || name.equals("connection")
                        || name.equals("cookie")
                        || name.equals("accept-encoding")) {
                    continue;
                }
                headerLines.add("      '" + escapeJs(header.name()) + "': '"
                        + escapeJs(header.value()) + "'");
            }
            headers.append(String.join(",\n", headerLines));
            if (!headerLines.isEmpty()) {
                headers.append("\n");
            }
        }
        headers.append("    }");

        // Note: cookies are NOT added as headers — k6 cookie jar manages
        // JSESSIONID automatically

        // Tag for per-request metrics in k6 summary
        String requestTag = requestTag(index, method, url);

        // Generate the request (use 'let' only for first request)
        String responseDecl = index == 0 ? "let response" : "response";

        if ("GET".equals(method) || "HEAD".equals(method)
                || "OPTIONS".equals(method)) {
            code.append("  ").append(responseDecl).append(" = http.")
                    .append(method.toLowerCase()).append("(\n");
            if (dynamicUrl) {
                String escapedUrl = UI_ID_URL_PATTERN
                        .matcher(escapeJsTemplate(url))
                        .replaceAll(Matcher.quoteReplacement("v-uiId=${uiId}"));
                code.append("    `").append(escapedUrl).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(url)).append("',\n");
            }
            code.append("    {\n");
            code.append("      headers: ").append(headers).append(",\n");
            code.append("      tags: { name: '").append(escapeJs(requestTag))
                    .append("' }\n");
            code.append("    }\n");
            code.append("  )\n\n");
        } else {
            // POST, PUT, PATCH, DELETE with body
            String body = "";
            if (request.postData() != null
                    && request.postData().text() != null) {
                body = request.postData().text();
            }
            boolean hasCsrfToken = pastInit
                    && CSRF_TOKEN_BODY_PATTERN.matcher(body).find();
            boolean hasSyncCounters = pastInit
                    && SYNC_CLIENT_ID_PATTERN.matcher(body).find();
            // Detect mSync input values (user-entered form data)
            List<String> msyncValues = new ArrayList<>();
            boolean hasMsyncInputs = false;
            if (pastInit) {
                Matcher msyncMatcher = MSYNC_INPUT_VALUE_PATTERN.matcher(body);
                while (msyncMatcher.find()) {
                    msyncValues.add(msyncMatcher.group(1));
                    hasMsyncInputs = true;
                }
            }

            // Classify positive "node":N occurrences as either resolvable
            // (we have a stable key from a prior response) or unresolved (no
            // recorded attachment). Negative IDs are client-side temporary
            // nodes and never match POSITIVE_NODE_ID_PATTERN.
            boolean hasResolvableNodeIds = false;
            Set<Integer> unresolvedNodeIds = new LinkedHashSet<>();
            if (resolveNodeIds && pastInit) {
                Matcher nm = POSITIVE_NODE_ID_PATTERN.matcher(body);
                while (nm.find()) {
                    int id = Integer.parseInt(nm.group(1));
                    if (nodeIdToStableKey.containsKey(id)) {
                        hasResolvableNodeIds = true;
                    } else {
                        unresolvedNodeIds.add(id);
                    }
                }
            }

            // Body needs template literals if it contains any dynamic values
            boolean dynamicBody = hasCsrfToken || hasSyncCounters
                    || hasMsyncInputs || hasResolvableNodeIds;

            // Detect grid entity key args in select/setDetailsVisible calls
            String entityKey = null;
            if (dynamicBody) {
                Matcher entityKeyMatcher = ENTITY_KEY_ARG_PATTERN.matcher(body);
                if (entityKeyMatcher.find()) {
                    entityKey = entityKeyMatcher.group(2);
                }
            }

            // Pick a random grid key before requests that select/edit entities
            if (entityKey != null) {
                code.append(
                        "  selectedKey = gridKeys.length > 0 ? gridKeys[Math.floor(Math.random() * gridKeys.length)] : '0'\n");
            }

            // Diagnostic comment for node IDs we never saw in any response —
            // leaves the original literal in the body so the request can
            // still be sent, but makes the condition visible to the reader.
            for (Integer unresolved : unresolvedNodeIds) {
                code.append("  /* unresolved node ").append(unresolved)
                        .append(" */\n");
            }

            // k6 uses http.del() for DELETE, not http.delete()
            String k6Method = "DELETE".equals(method) ? "del"
                    : method.toLowerCase();
            code.append("  ").append(responseDecl).append(" = http.")
                    .append(k6Method).append("(\n");

            if (dynamicUrl) {
                String escapedUrl = UI_ID_URL_PATTERN
                        .matcher(escapeJsTemplate(url))
                        .replaceAll(Matcher.quoteReplacement("v-uiId=${uiId}"));
                code.append("    `").append(escapedUrl).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(url)).append("',\n");
            }

            if (dynamicBody) {
                String escapedBody = escapeJsTemplate(body);
                // Replace hardcoded csrfToken UUID with dynamic variable
                if (hasCsrfToken) {
                    escapedBody = CSRF_TOKEN_BODY_PATTERN.matcher(escapedBody)
                            .replaceAll(Matcher.quoteReplacement(
                                    "\"csrfToken\":\"${csrfToken}\""));
                }
                // Replace hardcoded syncId/clientId with dynamic variables
                if (hasSyncCounters) {
                    escapedBody = SYNC_CLIENT_ID_PATTERN.matcher(escapedBody)
                            .replaceFirst(Matcher.quoteReplacement(
                                    "\"syncId\":${syncId},\"clientId\":${clientId}"));
                }
                // Replace hardcoded entity keys with dynamic grid key
                if (entityKey != null) {
                    escapedBody = escapedBody.replace(
                            "templateEventMethodArgs\":[\"" + entityKey + "\"]",
                            "templateEventMethodArgs\":[\"${selectedKey}\"]");
                }
                // Replace mSync input values with CSV data references
                for (String msyncValue : msyncValues) {
                    int inputIndex = collectedInputValues.size() + 1; // 1-based
                    collectedInputValues.add(msyncValue);
                    String escapedValue = escapeJsTemplate(msyncValue);
                    escapedBody = escapedBody.replaceFirst(
                            Pattern.quote("\"property\":\"value\",\"value\":\""
                                    + escapedValue + "\""),
                            Matcher.quoteReplacement(
                                    "\"property\":\"value\",\"value\":\"${inputRow.input_"
                                            + inputIndex + "}\""));
                }
                // Replace resolvable positive node IDs with the runtime
                // nodeMap accessor. Unresolvable matches stay literal so the
                // server receives the original (possibly stale) number.
                if (hasResolvableNodeIds) {
                    escapedBody = rewriteResolvableNodeIds(escapedBody);
                }
                code.append("    `").append(escapedBody).append("`,\n");
            } else {
                code.append("    '").append(escapeJs(body)).append("',\n");
            }

            code.append("    {\n");
            code.append("      headers: ").append(headers).append(",\n");
            code.append("      tags: { name: '").append(escapeJs(requestTag))
                    .append("' }\n");
            code.append("    }\n");
            code.append("  )\n\n");
        }

        // Universal status check so `checks rate==1` has data and failures
        // are attributable to a specific request in the summary. Logs the
        // status, URL, and a body snippet on failure so users can diagnose
        // what went wrong without rerunning with extra tracing.
        code.append(
                "  if (!check(response, { 'status < 400': (r) => r.status < 400 }, { name: '")
                .append(escapeJs(requestTag)).append("' })) {\n");
        code.append("    console.error(`").append(escapeJsTemplate(requestTag))
                .append(": HTTP ${response.status} ${response.url} - ${String(response.body).substring(0, 200)}`)\n");
        code.append("  }\n\n");

        return code.toString();
    }

    /**
     * Generates a short tag name for a request, used by k6 to create
     * per-request sub-metrics in the summary. Includes the scenario name so
     * that tags remain unique when multiple scenarios are combined.
     *
     * @param index
     *            0-based request index
     * @param method
     *            HTTP method
     * @param url
     *            the request URL
     * @return a descriptive tag (e.g., "hello-world: 1 GET init")
     */
    private String requestTag(int index, String method, String url) {
        String type;
        if (url.contains("v-r=init")) {
            type = "init";
        } else if (url.contains("v-r=uidl")) {
            type = "uidl";
        } else {
            try {
                java.net.URI uri = java.net.URI.create(url);
                type = uri.getPath();
                if (type == null || type.isEmpty() || type.equals("/")) {
                    type = "/";
                }
                // Collapse long hex hashes (e.g. Vite/Rollup chunk content
                // hashes) so tags stay readable:
                // /VAADIN/build/chunk-<64-hex>-DUiDBZUT.js
                // -> /VAADIN/build/chunk-...-DUiDBZUT.js
                type = type.replaceAll("[a-f0-9]{16,}", "...");
                if (type.length() > 120) {
                    type = type.substring(0, 117) + "...";
                }
            } catch (Exception e) {
                type = "/";
            }
        }
        return scenarioName + ": " + (index + 1) + " " + method + " " + type;
    }

    /**
     * Detects Vaadin session values from HAR entries. Finds all init requests,
     * recorded JSESSIONID, csrfToken, and uiId. Supports login flows where a
     * second init request occurs after authentication.
     *
     * @param entries
     *            the HAR entries to scan
     * @return session info if a Vaadin init request is found, null otherwise
     */
    private VaadinSessionInfo detectVaadinSession(List<HarEntry> entries) {
        int firstInitRequestIndex = -1;
        List<Integer> allInitRequestIndices = new ArrayList<>();
        String jsessionId = null;
        String csrfToken = null;
        String uiId = null;

        Pattern csrfPattern = Pattern
                .compile("\"csrfToken\"\\s*:\\s*\"([^\"]+)\"");
        Pattern uiIdPattern = Pattern.compile("v-uiId=(\\d+)");

        for (int i = 0; i < entries.size(); i++) {
            HarEntry entry = entries.get(i);
            String url = entry.request().url();

            // Find all init requests (login flows have multiple)
            if (url.contains("v-r=init")) {
                allInitRequestIndices.add(i);
                if (firstInitRequestIndex == -1) {
                    firstInitRequestIndex = i;
                }
            }

            // Find JSESSIONID from cookies
            if (jsessionId == null && entry.request().cookies() != null) {
                for (HarCookie cookie : entry.request().cookies()) {
                    if ("JSESSIONID".equalsIgnoreCase(cookie.name())) {
                        jsessionId = cookie.value();
                        break;
                    }
                }
            }

            // Find csrfToken from POST body
            if (csrfToken == null && entry.request().postData() != null
                    && entry.request().postData().text() != null) {
                Matcher m = csrfPattern
                        .matcher(entry.request().postData().text());
                if (m.find()) {
                    csrfToken = m.group(1);
                }
            }

            // Find uiId from URL
            if (uiId == null) {
                Matcher m = uiIdPattern.matcher(url);
                if (m.find()) {
                    uiId = m.group(1);
                }
            }
        }

        if (firstInitRequestIndex >= 0) {
            log.info(
                    "  Detected Vaadin session: initRequests="
                            + allInitRequestIndices.size() + " (first=#"
                            + (firstInitRequestIndex + 1) + ")" + ", uiId="
                            + uiId + ", csrfToken="
                            + (csrfToken != null ? csrfToken.substring(0,
                                    Math.min(8, csrfToken.length())) + "..."
                                    : "null"));
            return new VaadinSessionInfo(firstInitRequestIndex,
                    allInitRequestIndices, jsessionId, csrfToken, uiId);
        }
        return null;
    }

    /**
     * Generates k6 code to extract Vaadin session values from the init
     * response. This code is injected after the init request in the generated
     * script.
     *
     * @param requestLabel
     *            human-readable label for error messages (e.g., "Request 6 (GET
     *            ...)")
     * @param responseCheckConfig
     *            custom response checks to inject
     * @return the generated extraction code
     */
    private String generateSessionExtractionCode(String requestLabel,
            ResponseCheckConfig responseCheckConfig) {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Abort iteration and trigger test abort if init response is invalid\n");
        code.append("  if (!check(response, {\n");
        code.append("    'init request succeeded': (r) => r.status === 200,\n");
        code.append(
                "    'session is valid': (r) => !r.body.includes('Your session needs to be refreshed'),\n");
        code.append(
                "    'valid init response': (r) => r.body.includes('\"v-uiId\"') && r.body.includes('\"Vaadin-Security-Key\"'),\n");
        code.append(responseCheckConfig
                .toK6CheckLines(ResponseCheckConfig.Scope.INIT));
        code.append("  })) {\n");
        code.append("    fail(`").append(escapeJsTemplate(requestLabel)).append(
                ": init failed (status ${response.status}): ${response.body.substring(0, 200)}`)\n");
        code.append("  }\n\n");
        code.append("  // Extract Vaadin session values from init response\n");
        code.append(
                "  let uiId = response.body.match(/\"v-uiId\"\\s*:\\s*(\\d+)/)[1]\n");
        code.append(
                "  let csrfToken = response.body.match(/\"Vaadin-Security-Key\"\\s*:\\s*\"([^\"]+)\"/)[1]\n");
        code.append("  let syncId = 0\n");
        code.append("  let clientId = 0\n");
        code.append("  let gridKeys = []\n");
        code.append("  let selectedKey = '0'\n");
        if (resolveNodeIds) {
            // Runtime map from stable keys (id attributes or tag#ordinal) to
            // server-assigned node IDs. Populated from UIDL responses by
            // updateNodeMap() so RPC payloads can resolve node references
            // even when the server allocates different IDs than were
            // recorded.
            code.append("  let nodeMap = {}\n");
            code.append("  nodeMap = updateNodeMap(nodeMap, response.body)\n");
        }
        code.append("\n");
        return code.toString();
    }

    /**
     * Generates k6 code to re-extract Vaadin session values after a subsequent
     * init request (e.g., after login when the security key changes). Uses
     * reassignment instead of let declarations since variables already exist.
     *
     * @return the generated re-extraction code
     */
    private String generateSessionReExtractionCode() {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Re-extract Vaadin session values after login/navigation\n");
        code.append(
                "  if (response.status === 200 && response.body.includes('\"Vaadin-Security-Key\"')) {\n");
        code.append(
                "    var newUiId = response.body.match(/\"v-uiId\"\\s*:\\s*(\\d+)/)\n");
        code.append(
                "    var newCsrf = response.body.match(/\"Vaadin-Security-Key\"\\s*:\\s*\"([^\"]+)\"/)\n");
        code.append("    if (newUiId) uiId = newUiId[1]\n");
        code.append("    if (newCsrf) csrfToken = newCsrf[1]\n");
        code.append("    syncId = 0\n");
        code.append("    clientId = 0\n");
        if (resolveNodeIds) {
            // Session restart (e.g. post-login) — the server wipes the node
            // state, so the old mappings are invalid. Rebuild from this
            // response's changes.
            code.append("    nodeMap = updateNodeMap({}, response.body)\n");
        }
        code.append("  }\n");
        code.append("\n");
        return code.toString();
    }

    /**
     * Generates k6 code to extract syncId from a UIDL response and increment
     * clientId. Injected after each UIDL POST in the generated script.
     *
     * @param requestLabel
     *            human-readable label for error messages (e.g., "Request 10
     *            (POST ...)")
     * @param responseCheckConfig
     *            custom response checks to inject
     * @return the generated extraction code
     */
    private String generateUidlResponseExtractionCode(String requestLabel,
            ResponseCheckConfig responseCheckConfig) {
        StringBuilder code = new StringBuilder();
        code.append(
                "  // Abort iteration and trigger test abort if UIDL response is invalid\n");
        code.append(
                "  var syncIdMatch = response.body.match(/\"syncId\"\\s*:\\s*(-?\\d+)/)\n");
        code.append("  if (!check(response, {\n");
        code.append("    'UIDL request succeeded': (r) => r.status === 200,\n");
        code.append(
                "    'no server error': (r) => !r.body.includes('\"appError\"'),\n");
        code.append(
                "    'no exception': (r) => !r.body.includes('Exception'),\n");
        code.append(
                "    'session is valid': (r) => !r.body.includes('Your session needs to be refreshed'),\n");
        code.append(
                "    'security key valid': (r) => !r.body.includes('Invalid security key'),\n");
        code.append("    'valid UIDL response': () => syncIdMatch !== null,\n");
        code.append(responseCheckConfig
                .toK6CheckLines(ResponseCheckConfig.Scope.UIDL));
        code.append("  })) {\n");
        code.append("    fail(`").append(escapeJsTemplate(requestLabel)).append(
                ": UIDL failed (status ${response.status}): ${response.body.substring(0, 200)}`)\n");
        code.append("  }\n\n");
        code.append(
                "  // Update Vaadin sync counters from response (-1 means UNDEFINED_SYNC_ID, treat as 0)\n");
        code.append("  syncId = Math.max(0, parseInt(syncIdMatch[1]))\n");
        code.append("  clientId++\n");
        code.append(
                "  // Extract grid item keys from response (used for select/edit operations)\n");
        code.append(
                "  var found = response.body.match(/\"key\":\"[^\"]+\"/g)\n");
        code.append(
                "  if (found) gridKeys = found.map(s => s.split('\"')[3])\n");
        if (resolveNodeIds) {
            // Refresh stable-key → node-ID bindings from the response's
            // changes stream so the next RPC payload can resolve them.
            code.append("  nodeMap = updateNodeMap(nodeMap, response.body)\n");
        }
        code.append("\n");
        return code.toString();
    }

    /**
     * Checks if a HAR entry is a Vaadin UIDL request.
     *
     * @param entry
     *            the HAR entry to check
     * @return {@code true} if the entry is a UIDL POST request
     */
    private boolean isUidlRequest(HarEntry entry) {
        return "POST".equalsIgnoreCase(entry.request().method())
                && entry.request().url().contains("v-r=uidl");
    }

    /**
     * Returns {@code true} for HAR entries whose response may carry a Vaadin
     * UIDL {@code changes} array — init GETs and UIDL POSTs. Other entries
     * (static assets, page HTML) are skipped to keep JSON parsing narrow.
     */
    private boolean isVaadinResponseEntry(HarEntry entry) {
        String url = entry.request().url();
        return isUidlRequest(entry) || url.contains("v-r=init");
    }

    /**
     * Extracts the response body text from a HAR entry, or {@code null} if no
     * text content is recorded.
     */
    private static String responseBodyText(HarEntry entry) {
        HarResponse response = entry.response();
        if (response == null || response.content() == null) {
            return null;
        }
        return response.content().text();
    }

    /**
     * Walks the {@code changes} array of a Vaadin UIDL response and records a
     * stable key for each {@code node} — either the element's {@code id}
     * attribute (preferred) or a {@code tag#ordinal} fallback. The conversion-
     * time map is used to rewrite subsequent request bodies; the runtime
     * {@code updateNodeMap} helper applies the same logic to the live response
     * inside each k6 virtual user.
     *
     * @param body
     *            the response body, with or without the Vaadin {@code for(;;);}
     *            script-tag-injection prefix
     */
    private void registerChangesFromResponse(String body) {
        if (body == null || body.isEmpty()) {
            return;
        }
        String trimmed = body;
        if (trimmed.startsWith(UIDL_RESPONSE_PREFIX)) {
            trimmed = trimmed.substring(UIDL_RESPONSE_PREFIX.length());
        }
        JsonNode root;
        try {
            root = objectMapper.readTree(trimmed);
        } catch (Exception e) {
            // Not JSON (e.g. init response is HTML) — skip silently.
            return;
        }
        if (root == null) {
            return;
        }
        if (root.isArray()) {
            for (JsonNode entry : root) {
                registerChangesFromEntry(entry);
            }
        } else if (root.isObject()) {
            // Some init responses wrap the UIDL payload in a top-level object
            // (e.g. {"uidl": "for(;;);[{...}]"}). Descend opportunistically.
            JsonNode changes = root.get("changes");
            if (changes != null) {
                registerChangesFromEntry(root);
            }
            JsonNode uidlField = root.get("uidl");
            if (uidlField != null && uidlField.isTextual()) {
                registerChangesFromResponse(uidlField.asText());
            }
        }
    }

    private void registerChangesFromEntry(JsonNode entry) {
        if (entry == null) {
            return;
        }
        JsonNode changes = entry.get("changes");
        if (changes == null || !changes.isArray()) {
            return;
        }
        for (JsonNode change : changes) {
            registerChange(change);
        }
    }

    private void registerChange(JsonNode change) {
        if (change == null) {
            return;
        }
        JsonNode nodeNode = change.get("node");
        if (nodeNode == null || !nodeNode.isInt()) {
            return;
        }
        int nodeId = nodeNode.asInt();
        if (nodeId <= 0) {
            // Client-side temp nodes aren't server-addressable; ignore.
            return;
        }
        JsonNode keyNode = change.get("key");
        JsonNode valueNode = change.get("value");
        String keyText = keyNode != null && keyNode.isTextual()
                ? keyNode.asText()
                : null;

        if ("id".equals(keyText) && valueNode != null
                && valueNode.isTextual()) {
            // id attributes win over any existing tag#N fallback entry.
            nodeIdToStableKey.put(nodeId, valueNode.asText());
            return;
        }

        String tag = null;
        if ("tag".equals(keyText) && valueNode != null
                && valueNode.isTextual()) {
            tag = valueNode.asText();
        } else {
            JsonNode tagNode = change.get("tag");
            if (tagNode != null && tagNode.isTextual()) {
                tag = tagNode.asText();
            }
        }
        if (tag != null) {
            int ordinal = ordinalByTag.merge(tag, 1, Integer::sum);
            // Preserve an earlier id-based key if we already recorded one.
            nodeIdToStableKey.putIfAbsent(nodeId, tag + "#" + ordinal);
        }
    }

    /**
     * Rewrites positive {@code "node":N} occurrences in an already-
     * template-literal-escaped body to reference the runtime {@code nodeMap}
     * via {@code resolveNode}. Unresolvable matches are left verbatim so the
     * server still receives a (possibly stale) literal number — the adjacent
     * diagnostic comment emitted by the caller is the visible signal.
     */
    private String rewriteResolvableNodeIds(String escapedBody) {
        Matcher m = POSITIVE_NODE_ID_PATTERN.matcher(escapedBody);
        StringBuilder sb = new StringBuilder();
        while (m.find()) {
            int id = Integer.parseInt(m.group(1));
            String key = nodeIdToStableKey.get(id);
            if (key != null) {
                String safeKey = key.replace("\\", "\\\\").replace("'", "\\'");
                m.appendReplacement(sb, Matcher.quoteReplacement(
                        "\"node\":${resolveNode(nodeMap, '" + safeKey + "')}"));
            }
            // else: skip — appendTail will copy the literal verbatim.
        }
        m.appendTail(sb);
        return sb.toString();
    }

    /**
     * Holds Vaadin session values detected from the recorded HAR file.
     */
    record VaadinSessionInfo(int initRequestIndex,
            List<Integer> allInitRequestIndices, String recordedJsessionId,
            String recordedCsrfToken, String recordedUiId) {
        /**
         * Returns true if the given index is an init request (but not the first
         * one).
         */
        boolean isSubsequentInitRequest(int index) {
            return allInitRequestIndices.contains(index)
                    && index != initRequestIndex;
        }
    }

    /**
     * Calculates time delta in milliseconds between two requests.
     *
     * @param previous
     *            the previous HAR entry
     * @param current
     *            the current HAR entry
     * @return time delta in milliseconds, or 0 if unable to calculate
     */
    private long calculateDeltaMs(HarEntry previous, HarEntry current) {
        try {
            if (previous.startedDateTime() != null
                    && current.startedDateTime() != null) {
                Instant prevTime = Instant.parse(previous.startedDateTime());
                Instant currTime = Instant.parse(current.startedDateTime());
                return Math.max(0,
                        currTime.toEpochMilli() - prevTime.toEpochMilli());
            }
        } catch (Exception e) {
            // Ignore parse errors
        }
        return 0;
    }

    /**
     * Truncates URL for display in comments.
     *
     * @param url
     *            the URL to truncate
     * @return the truncated URL (max 80 characters)
     */
    private String truncateUrl(String url) {
        if (url.length() > 80) {
            return url.substring(0, 77) + "...";
        }
        return url;
    }

    /**
     * Escapes a string for use in a JavaScript single-quoted string.
     *
     * @param str
     *            the string to escape
     * @return the escaped string
     */
    private String escapeJs(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("\\", "\\\\").replace("'", "\\'")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t");
    }

    /**
     * Escapes a string for use in a JavaScript template literal (backtick
     * string). Does NOT escape ${} — the caller is responsible for inserting
     * template expressions after calling this method.
     *
     * @param str
     *            the string to escape
     * @return the escaped string
     */
    private String escapeJsTemplate(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("\\", "\\\\").replace("`", "\\`")
                .replace("${", "\\${").replace("\n", "\\n").replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    // ── CSV input data support ─────────────────────────────────────────

    /**
     * Injects SharedArray import and CSV loading code into the generated
     * script. The CSV file contains recorded input values that can be expanded
     * by the user to provide different data for each virtual user.
     *
     * @param scriptContent
     *            the generated k6 script content
     * @param outputFile
     *            the output file path (used to derive the CSV file name)
     * @return the modified script content with CSV loading injected
     */
    private String addCsvDataLoading(String scriptContent, Path outputFile) {
        String csvFileName = deriveCsvPath(outputFile).getFileName().toString();

        // Add SharedArray import after existing imports
        scriptContent = scriptContent.replace("import { sleep } from 'k6'",
                "import { sleep } from 'k6'\nimport { SharedArray } from 'k6/data'");

        // Add RFC 4180 CSV parser and data loading
        String csvLoadBlock = "\n"
                + "// Input test data from CSV — add rows to " + csvFileName
                + " for per-VU variation\n"
                + "function parseCsvRecords(text) {\n"
                + "  const records = [], n = text.length\n" + "  let i = 0\n"
                + "  function parseField() {\n"
                + "    if (i < n && text[i] === '\"') {\n"
                + "      i++ // opening quote\n" + "      let f = ''\n"
                + "      while (i < n) {\n"
                + "        if (text[i] === '\"' && text[i + 1] === '\"') { f += '\"'; i += 2 }\n"
                + "        else if (text[i] === '\"') { i++; return f }\n"
                + "        else { f += text[i]; i++ }\n" + "      }\n"
                + "      return f\n" + "    }\n" + "    let f = ''\n"
                + "    while (i < n && text[i] !== ',' && text[i] !== '\\r' && text[i] !== '\\n') { f += text[i]; i++ }\n"
                + "    return f\n" + "  }\n" + "  while (i < n) {\n"
                + "    const row = []\n" + "    row.push(parseField())\n"
                + "    while (i < n && text[i] === ',') { i++; row.push(parseField()) }\n"
                + "    if (text[i] === '\\r') i++\n"
                + "    if (text[i] === '\\n') i++\n"
                + "    if (row.length > 1 || row[0] !== '') records.push(row)\n"
                + "  }\n" + "  return records\n" + "}\n\n"
                + "const inputData = new SharedArray('input data', function () {\n"
                + "  const records = parseCsvRecords(open('./" + csvFileName
                + "'))\n" + "  const headers = records[0]\n"
                + "  return records.slice(1).map(values => {\n"
                + "    const obj = {}\n"
                + "    headers.forEach((h, i) => obj[h.trim()] = (values[i] || '').trim())\n"
                + "    return obj\n" + "  })\n" + "})\n";

        String inputRowSelection = "  // Pick a random row from the input data CSV\n"
                + "  const inputRow = inputData[Math.floor(Math.random() * inputData.length)]\n\n";

        scriptContent = scriptContent.replace("export default function () {\n",
                csvLoadBlock + "\nexport default function () {\n"
                        + inputRowSelection);

        return scriptContent;
    }

    /**
     * Derives the CSV data file path from the k6 output file path. Strips
     * "-generated" suffix if present so both generated and refactored scripts
     * reference the same CSV file.
     *
     * @param outputFile
     *            the k6 output file path
     * @return the derived CSV file path
     */
    private Path deriveCsvPath(Path outputFile) {
        String fileName = outputFile.getFileName().toString();
        String csvName;
        if (fileName.endsWith("-generated.js")) {
            csvName = fileName.replace("-generated.js", "-data.csv");
        } else {
            csvName = fileName.replace(".js", "-data.csv");
        }
        return outputFile.resolveSibling(csvName);
    }

    /**
     * Writes the collected input values to a CSV file. The first row contains
     * column headers (input_1, input_2, ...). The second row contains the
     * values recorded during the TestBench test. Users can add more rows to
     * provide different data for each virtual user; if only the recorded row is
     * present it will be used for all VUs.
     *
     * @param csvFile
     *            the CSV file path to write
     * @throws IOException
     *             if writing fails
     */
    private void writeCsvFile(Path csvFile) throws IOException {
        StringBuilder csv = new StringBuilder();
        // Header row
        for (int i = 0; i < collectedInputValues.size(); i++) {
            if (i > 0)
                csv.append(',');
            csv.append("input_").append(i + 1);
        }
        csv.append('\n');
        // Data row with recorded values
        for (int i = 0; i < collectedInputValues.size(); i++) {
            if (i > 0)
                csv.append(',');
            csv.append(escapeCsvValue(collectedInputValues.get(i)));
        }
        csv.append('\n');
        Files.writeString(csvFile, csv.toString());
    }

    /**
     * Escapes a value for CSV output (RFC 4180). Wraps in double quotes if the
     * value contains commas, quotes, or newlines.
     *
     * @param value
     *            the value to escape
     * @return the escaped CSV value
     */
    static String escapeCsvValue(String value) {
        if (value.contains(",") || value.contains("\"") || value.contains("\n")
                || value.contains("\r")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    // HAR format DTOs using Java records
    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarFile(HarLog log) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarLog(String version, HarCreator creator, List<HarEntry> entries,
            List<HarPage> pages) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarCreator(String name, String version) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarPage(String startedDateTime, String id, String title) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarEntry(String startedDateTime, Double time, HarRequest request,
            HarResponse response) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarRequest(String method, String url, String httpVersion,
            List<HarHeader> headers, List<HarCookie> cookies,
            HarPostData postData) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarResponse(Integer status, String statusText,
            List<HarHeader> headers, HarContent content) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarHeader(String name, String value) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarCookie(String name, String value) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarPostData(String mimeType, String text) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    record HarContent(Long size, String mimeType, String text) {
    }
}
