name: Maven Format Validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run formatter:validate
        run: mvn formatter:validate --batch-mode --no-transfer-progress
